---
framework: mocha
preRun:
     command:
        - npm install
        - nom run prepare
preMerge:
  pattern:
    - "./test/index.js"
postMerge:
  pattern: 
    - "./test/index.js"
postRun:
     command:
        - node --version
version: 1.0
